route:
  receiver: 'pagerduty'
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: 'pagerduty'
    pagerduty_configs:
    - routing_key_file: /etc/alertmanager/pd-routing-key.example