version: '3.8'

services:
  prometheus-example-app:
    image: gesarki/prometheus-example-app
    ports:
      - "8080:8080"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    restart: unless-stopped


volumes:
  prometheus-data:
