global:
  scrape_interval: 5s  # How often to scrape targets by default
  evaluation_interval: 5s  # How often to evaluate rules

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

rule_files:
  - rules.yml

# Where do we want alerts sent to?
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"