global:
  scrape_interval: 5s  # How often to scrape targets by default
  evaluation_interval: 5s  # How often to evaluate rules

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'prometheus-example-app'
    static_configs:
      - targets: ['prometheus-example-app:8080']

