groups:
- name: example
  rules:
  - alert: HighHttpInternalErrorCount
    expr: increase(http_requests_total{job="prometheus-example-app", code=~"5[0-9][0-9]"}[1m]) > 20
    for: 1m
    keep_firing_for: 1m
    labels:
      severity: page
    annotations:
      summary: High 5xx error count
